#Jekyll configuration


markdown: kramdown
permalink: /:year/:month/:title/
url: https://chenhongbiao.github.io/en
author: Chen Hongbiao

# pygments is unsupported now. use rouge instead. 
pygments: false
rouge: true

